[project]
authors = ["enriquegomeztagle <0241823@up.edu.mx>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "logger"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
